
services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis-data:/data

  postgres:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-cuddlecat}
      POSTGRES_USER: ${POSTGRES_USER:-cuddle}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cuddlepass}
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - DATA_DIR=${DATA_DIR:-/data}
      - EMBED_MODEL=${EMBED_MODEL:-moka-ai/m3e-small}
      - MEMORY_VECTOR_SCORE_THRESHOLD=${MEMORY_VECTOR_SCORE_THRESHOLD:-0.6}
      - METRICS_API_KEY=${METRICS_API_KEY:-}
      - AI_SERVICE_INTERNAL_KEY=${AI_SERVICE_INTERNAL_KEY:-}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-cuddlecat}
      - POSTGRES_USER=${POSTGRES_USER:-cuddle}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-cuddlepass}
      # Or use DSN:
      # - POSTGRES_DSN=postgresql+psycopg://cuddle:cuddlepass@postgres:5432/cuddlecat
    volumes:
      - server-data:/data
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres

networks:
  default:
    driver: bridge


volumes:
  server-data:
  redis-data:
  pg-data:

