name: cuddle_cat
description: "一款基于 AI 驱动的心理健康与情感陪伴应用"
version: 1.0.0+1

homepage: https://github.com/miaowumiaowu/cuddle_cat
repository: https://github.com/miaowumiaowu/cuddle_cat
issue_tracker: https://github.com/miaowumiaowu/cuddle_cat/issues

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  lottie: ^3.1.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10+1
  intl: ^0.18.1
  uuid: ^4.3.3
  http: ^1.2.1
  flutter_dotenv: ^5.1.0

  # 位置服务 (简化方案，避免网络问题)

  # 移除有问题的地图依赖，使用自定义地图方案

  # 多媒体处理
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.8.3
  flutter_image_compress: ^2.1.0
  video_player: ^2.8.1
  audio_waveforms: ^1.0.5

  # 网络和数据处理
  dio: ^5.4.0
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1

  # 图表可视化
  fl_chart: ^0.68.0

  # 心情和支出记录
  sqflite: ^2.3.0
  audioplayers: ^6.5.0
  table_calendar: ^3.0.9
  flutter_local_notifications: ^19.4.0
  permission_handler: ^12.0.1
  google_fonts: ^6.3.0
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/base/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
